# Generated by Django 5.1 on 2024-09-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="banner",
            field=models.ImageField(blank=True, default="fallback.jpg", upload_to=""),
        ),
    ]
